<?php

namespace EmpresasBundle\Repository;

/**
 * EmpresasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresasRepository extends \Doctrine\ORM\EntityRepository
{
}
